package com.bupt.dao.mapper;

import com.bupt.dao.entity.Bgm;
import com.bupt.dao.entity.BgmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.context.annotation.Configuration;
import org.springframework.stereotype.Component;

@Component
public interface BgmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Sat Jan 04 21:33:45 CST 2020
     */
    long countByExample(BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Sat Jan 04 21:33:45 CST 2020
     */
    int deleteByExample(BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Sat Jan 04 21:33:45 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Sat Jan 04 21:33:45 CST 2020
     */
    int insert(Bgm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Sat Jan 04 21:33:45 CST 2020
     */
    int insertSelective(Bgm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Sat Jan 04 21:33:45 CST 2020
     */
    List<Bgm> selectByExample(BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Sat Jan 04 21:33:45 CST 2020
     */
    Bgm selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Sat Jan 04 21:33:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") Bgm record, @Param("example") BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Sat Jan 04 21:33:45 CST 2020
     */
    int updateByExample(@Param("record") Bgm record, @Param("example") BgmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Sat Jan 04 21:33:45 CST 2020
     */
    int updateByPrimaryKeySelective(Bgm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Sat Jan 04 21:33:45 CST 2020
     */
    int updateByPrimaryKey(Bgm record);
}
