package com.bupt.dao.mapper;

import com.bupt.dao.entity.Videos;
import com.bupt.dao.entity.VideosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sat Jan 04 21:40:31 CST 2020
     */
    long countByExample(VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sat Jan 04 21:40:31 CST 2020
     */
    int deleteByExample(VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sat Jan 04 21:40:31 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sat Jan 04 21:40:31 CST 2020
     */
    int insert(Videos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sat Jan 04 21:40:31 CST 2020
     */
    int insertSelective(Videos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sat Jan 04 21:40:31 CST 2020
     */
    List<Videos> selectByExample(VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sat Jan 04 21:40:31 CST 2020
     */
    Videos selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sat Jan 04 21:40:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") Videos record, @Param("example") VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sat Jan 04 21:40:31 CST 2020
     */
    int updateByExample(@Param("record") Videos record, @Param("example") VideosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sat Jan 04 21:40:31 CST 2020
     */
    int updateByPrimaryKeySelective(Videos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Sat Jan 04 21:40:31 CST 2020
     */
    int updateByPrimaryKey(Videos record);
}