server:
  port: 8888
  servlet:
    context-path: /coolvideo

spring:
  datasource:
    url: jdbc:mysql://www.huangxin388.top:3306/coolvideo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#Mybatis
mybatis:
  #加载mybatis主要配置类
  config-location: classpath:/mybatis-config.xml
  #加载mapper配置类
  mapper-locations: classpath:/mapper/*.xml
  #加载mapper实体类
#  type-aliases-package: com.bupt.dao.entity
