package com.bupt.dao.entity;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.USER
     *
     * @mbg.generated Sat Jan 04 21:38:44 CST 2020
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.CURRENT_CONNECTIONS
     *
     * @mbg.generated Sat Jan 04 21:38:44 CST 2020
     */
    private Long currentConnections;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.TOTAL_CONNECTIONS
     *
     * @mbg.generated Sat Jan 04 21:38:44 CST 2020
     */
    private Long totalConnections;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USER
     *
     * @return the value of users.USER
     *
     * @mbg.generated Sat Jan 04 21:38:44 CST 2020
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USER
     *
     * @param user the value for users.USER
     *
     * @mbg.generated Sat Jan 04 21:38:44 CST 2020
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.CURRENT_CONNECTIONS
     *
     * @return the value of users.CURRENT_CONNECTIONS
     *
     * @mbg.generated Sat Jan 04 21:38:44 CST 2020
     */
    public Long getCurrentConnections() {
        return currentConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.CURRENT_CONNECTIONS
     *
     * @param currentConnections the value for users.CURRENT_CONNECTIONS
     *
     * @mbg.generated Sat Jan 04 21:38:44 CST 2020
     */
    public void setCurrentConnections(Long currentConnections) {
        this.currentConnections = currentConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.TOTAL_CONNECTIONS
     *
     * @return the value of users.TOTAL_CONNECTIONS
     *
     * @mbg.generated Sat Jan 04 21:38:44 CST 2020
     */
    public Long getTotalConnections() {
        return totalConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.TOTAL_CONNECTIONS
     *
     * @param totalConnections the value for users.TOTAL_CONNECTIONS
     *
     * @mbg.generated Sat Jan 04 21:38:44 CST 2020
     */
    public void setTotalConnections(Long totalConnections) {
        this.totalConnections = totalConnections;
    }
}